task_manager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from tasks import urls as task_urls
from rest_framework.routers import DefaultRouter
from tasks.api.views import TaskViewSet
router = DefaultRouter()
router.register(r'tasks', TaskViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include(task_urls, namespace='tasks')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import TaskListView,TaskAdd,TaskUpdate,TaskView,TaskDelete

app_name='tasks'

urlpatterns = [
    path('add-task', TaskAdd.as_view(), name="add_task"),
    path('', TaskListView.as_view(), name="all_tasks"),
    path('update-task/<int:pk>', TaskUpdate.as_view(), name="update_task"),
    path('view-task/<int:pk>', TaskView.as_view(), name="view_task"),
    path('delete-task/<int:pk>', TaskDelete.as_view(), name="delete_task"),

]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    PRIORITY_CHOICES = [
        ('Low', 'Low'),
        ('Medium', 'Medium'),
        ('High', 'High'),
    ]

    title = models.CharField(max_length=255)
    description = models.TextField()
    creation_date_time = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField()
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default='Medium')
    completed = models.BooleanField(default=False)
    photos = models.ManyToManyField('Photo', blank=True, related_name='task_photo')
    assign_user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)
    def __str__(self):
        return self.title

class Photo(models.Model):
    image = models.FileField(upload_to='tasks/photos/')
    
    def __str__(self):
        return str(self.image)

   

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'creation_date_time': forms.TextInput(attrs={'class': 'form-control'}),
            'due_date': forms.TextInput(attrs={'class': 'form-control'}),
            'priority':  forms.Select(attrs={'class': 'form-control'}),
            'completed': forms.TextInput(attrs={'class': 'form-control'}),
            'photos': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'assign_user':  forms.Select(attrs={'class': 'form-control'}),
            
        }
class TaskSearchForm(forms.Form):
    search_query = forms.CharField(label='Search', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))

tasks/api/views.py
from rest_framework import viewsets
from .serializers import TaskSerializers
from tasks.models import Task

class TaskViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializers
    

tasks/views.py
from django.views.generic import ListView, DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.db import models
from .models import Task
from .forms import TaskForm
from .forms import TaskSearchForm
from django.db.models import Q

class TaskListView(ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'tasks/all.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search_query')

        if search_query:
            queryset = queryset.filter(
               Q(title__icontains=search_query) |
               Q(description__icontains=search_query) |
               Q(priority__icontains=search_query) |
               Q(creation_date_time__icontains=search_query) |
               Q(due_date__icontains=search_query) |
               Q(completed__icontains=search_query)
            )

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TaskSearchForm(self.request.GET)
        return context

# class TaskListView(ListView):
#     model = Task
#     context_object_name = 'tasks'
#     template_name = 'tasks/all.html'
    
class TaskAdd(CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/add.html'
    success_url= reverse_lazy('tasks:all_tasks')
    
class TaskUpdate(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/update.html'
    success_url= reverse_lazy('tasks:all_tasks') 
    
    
class TaskView(DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'tasks/view.html' 
    
class TaskDelete(DeleteView):
    model = Task
    template_name = 'tasks/tasks_confirm_delete.html' 
    success_url= reverse_lazy('tasks:all_tasks')  
    


# class TaskListView(ListView):
#     model = Task
#     context_object_name = 'tasks'
#     template_name = 'tasks/all.html'
#     paginate_by = 10  # Adjust as needed

#     def get_queryset(self):
#         queryset = super().get_queryset()

#         # Get the search parameters from the request
#         title_query = self.request.GET.get('title', '')
#         creation_date_time_query = self.request.GET.get('creation_date_time', '')
#         due_date_query = self.request.GET.get('due_date', '')
#         priority_query = self.request.GET.get('priority', '')
#         completed_query = self.request.GET.get('completed', '')

#         # Filter tasks based on search parameters
#         if title_query:
#             queryset = queryset.filter(title__icontains=title_query)

#         if creation_date_time_query:
#             queryset = queryset.filter(creation_date_time__icontains=creation_date_time_query)

#         if due_date_query:
#             queryset = queryset.filter(due_date=due_date_query)

#         if priority_query:
#             queryset = queryset.filter(priority=priority_query)

#         if completed_query:
#             queryset = queryset.filter(completed=completed_query.lower() == 'true')

#         return queryset
                       

tasks/templates/tasks/add.html
{% extends 'tasks/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               <div class="card-header ">
                  <div class="row">
                     <div class="col-md-11 card_header_title">
                        <i class="fab fa-gg-circle"></i>
                        Add Task 
                     </div>
                     <div class="col-md-1 text-right card_header_btn">
                        <a class="btn btn-sm btn-secondary" href="{% url 'tasks:all_tasks' %}">
                        <i class="fas fa-th fa-lg"></i>
                        All Task Logs
                        </a>
                     </div>
                  </div>
                  <div class="clr"></div>
               </div>
               <div class="card-body">
                  {{ form }}
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">SAVE</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

tasks/templates/tasks/all.html
{% extends 'tasks/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
   
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title"></h4>
                <div class="page-title-right">
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <!-- Content in the first column (if any) -->
        </div>
        <div class="col-md-2 d-flex align-items-end">
            <form method="get" action="">
                <div class="form-group mb-0">
                    <div class="input-group">
                        <input type="text" class="form-control" id="search_query" name="search_query" value="{{ request.GET.search_query }}" placeholder="Search">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-secondary">Search</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div><br>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-11 card_header_title">
                            <i class="fab fa-gg-circle"></i>
                            All Task Log
                        </div>
                        <div class="col-md-1 text-right card_header_btn">
                            <a class="btn btn-sm btn-secondary" href="{% url 'tasks:add_task' %}">
                                <i class="fa fa-plus-circle"></i>
                                Add Task
                            </a>
                        </div>
                    </div>
                    <div class="clr"></div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <table id="allTableInfo" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                <thead class="">
                                    <tr>
                                        <th>Task Name </th>
                                        <th>Description</th>
                                       
                                        <th>Priority </th>
                                        <th>Created</th>
                                        <th>Due Date</th>
                                        <th>Completed</th>
                                        <th>Photos</th>

                                      
                                        <th>Manage</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for task in tasks %}
                                        <tr>
                                            <td>{{ task.title }}</td>
                                            <td>{{ task.description }}</td>
                                            <td>{{ task.priority }}</td>
                                            <td>{{ task.creation_date_time }}</td>
                                            <td>{{ task.due_date }}</td>
                                            <td>{{task.completed}}</td>
                                
                                            <!-- Displaying photos associated with the task -->
                                            <td>
                                                {% if task.photos.all %}
                                                    {% for photo in task.photos.all %}
                                                        <img src="{{ photo.image.url }}" alt="{{ task.title }} - Photo" style="max-width: 100px; max-height: 100px;">
                                                    {% endfor %}
                                                {% else %}
                                                    No photos available
                                                {% endif %}
                                            </td>
                                
                                            <td>
                                    
                                            <ul>
                                            <li><a href="{% url 'tasks:view_task' task.id %}" class="dropdown-item">View</a></li>
                                            <li><a href="{% url 'tasks:update_task' task.id %}" class="dropdown-item">Edit</a></li>
                                            <li><a href="{% url 'tasks:delete_task' task.id %}"class="dropdown-item">Delete</a></li>    
                                            </ul>
                                            </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <!-- <div class="btn-group">
                        <button type="button" class="btn btn-purple waves-effect">PRINT</button>
                        <button type="button" class="btn btn-dark waves-effect">PDF</button>
                        <button type="button" class="btn btn-pink waves-effect">EXEL</button>
                        <button type="button" class="btn btn-success waves-effect">CSV</button>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
    <!--delete model code start-->
    <!-- <div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <form method="post" action="#">
        
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="myModalLabel"><i class="fab fa-gg-circle"></i> Confirm Message</h5>
                    </div>
                    <div class="modal-body modal_body">
                        Are you sure to delete this information?
                        <input type="hidden" name="modal_id" id="modalID" value="" />
                    </div>
                    <div class="modal-footer modal_footer">
                        <button type="button" class="btn btn-sm btn-success waves-effect" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-sm btn-danger waves-effect waves-light">Yes</button>
                    </div>
                </div>
            </form>
        </div>
    </div> -->
</div>
{% endblock content %}

tasks/templates/tasks/base.html
<!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Task-Manager</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
  <body><br><br>
    <div class="content">
               
                  {% block content %}
                  {%endblock content%}
               
            </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

tasks/templates/tasks/tasks_confirm_delete.html
{% extends 'tasks/base.html' %}
{% load static %}
{% block content %}
<!-- Start Content-->
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <!-- <h4 class="page-title"></h4>
            <div class="page-title-right">
               <ol class="breadcrumb p-0 m-0">
                  <li class="breadcrumb-item"><a href="#"></a></li>
                  <li class="breadcrumb-item"><a href="#"></a></li>
                  <li class="breadcrumb-item active"></li>
               </ol>
            </div> -->
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">Delete</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

tasks/templates/tasks/update.html
{% extends 'tasks/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               <div class="card-header ">
                  <div class="row">
                     <div class="col-md-11 card_header_title">
                        <i class="fab fa-gg-circle"></i>
                         Update Task Log
                     </div>
                     <div class="col-md-1 text-right card_header_btn">
                        <a class="btn btn-sm btn-secondary" href="{% url 'tasks:all_tasks' %}">
                        <i class="fas fa-th fa-lg"></i>
                        All Task Logs
                        </a>
                     </div>
                  </div>
                  <div class="clr"></div>
               </div>
               <div class="card-body">
                  {{form}}
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">Update</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

tasks/templates/tasks/view.html
{% extends 'tasks/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
       <div class="col-12">
          <div class="page-title-box">

             <div class="clearfix"></div>
          </div>
       </div>
    </div>
    <div class="row">
       <div class="col-lg-12">
          <div class="card">
             <div class="card-header">
                <div class="row">
                   <div class="col-md-11 card_header_title">
                      <i class="fab fa-gg-circle"></i>
                      View Task Log
                   </div>
                   <div class="col-md-1 text-right card_header_btn">
                      <a class="btn btn-sm btn-secondary" href="{% url 'tasks:all_tasks' %}">
                      <i class="fa fa-plus-circle"></i>
                      All Tasks Logs
                      </a>
                   </div>
                </div>
                <div class="clr"></div>
             </div>
             <div class="card-body">
                <div class="row">
                   <div class="col-md-2 col-sm-2 col-2"></div>
                   <div class="col-md-8 col-sm-8 col-8">
                      <table class="table table-bordered table-striped custom_view_table">
                        <tr>
                           <td>Task Name</td>
                           <td>:</td>
                           <td>{{task.title}}</td>
                        </tr>
                         <tr>
                            <td>Description</td>
                            <td>:</td>
                            <td>{{task.description}} </td>
                         </tr>
                         <tr>
                            <td>Photo</td>
                            <td>:</td>
                            <td>
                              {% if task.photos.all %}
                                  {% for photo in task.photos.all %}
                                      <img src="{{ photo.image.url }}" alt="{{ task.title }} - Photo" style="max-width: 100px; max-height: 100px;">
                                  {% endfor %}
                              {% else %}
                                  No photos available
                              {% endif %}
                          </td>
                         </tr>
                         
                      </table>
                   </div>
                   <div class="col-md-2 col-sm-2 col-2"></div>
                </div>
             </div>
             <div class="card-footer">
                <!-- <div class="btn-group">
                   <button type="button" class="btn btn-purple waves-effect">PRINT</button>
                   <button type="button" class="btn btn-dark waves-effect">PDF</button>
                   <button type="button" class="btn btn-pink waves-effect">EXEL</button>
                   <button type="button" class="btn btn-success waves-effect">CSV</button>
                </div> -->
             </div>
          </div>
       </div>
    </div>
 </div>
{% endblock content %}